[package]
name = "minidump-unwind"
description = "A library for producing stack traces from minidump files."
version = "0.19.1"
authors = ["Alex Franchuk <afranchuk@mozilla.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/rust-minidump/rust-minidump"
repository = "https://github.com/rust-minidump/rust-minidump"
edition = "2018"

[badges]
travis-ci = { repository = "rust-minidump/rust-minidump" }

[features]
# Allows retrieval of symbols from debug info.
debuginfo = ["cachemap2", "futures-util", "memmap2", "symbolic-cfi", "symbolic-common", "symbolic-debuginfo", "symbolic-demangle"]
# Allows demangling of swift symbols in debug info.
swift = ["debuginfo", "symbolic-demangle/swift"]
# Allows retrieval of symbol files via HTTP
http = ["breakpad-symbols/http"]

[dependencies]
async-trait = "0.1.52"
breakpad-symbols = { version = "0.19.1", path = "../breakpad-symbols" }
cachemap2 = { version = "0.2.0", optional = true }
futures-util = { version = "0.3.25", optional = true }
memmap2 = { version = "0.8", optional = true }
minidump = { version = "0.19.1", path = "../minidump" }
minidump-common = { version = "0.19.1", path = "../minidump-common" }
scroll = "0.11.0"
symbolic-cfi = { version = "12", optional = true }
symbolic-common = { version = "12", optional = true }
symbolic-debuginfo = { version = "12", optional = true }
symbolic-demangle = { version = "12", default-features = false, features = ["cpp", "msvc", "rust"], optional = true }
tracing = { version = "0.1.34", features = ["log"] }

[dev-dependencies]
doc-comment = "0.3.3"
test-assembler = "0.1.6"
tokio = { version = "1.34.0", features = ["full"] }

[package.metadata.docs.rs]
all-features = true
